#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDiakont
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TestDiakont")]
	public partial class DCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBetwRate(BetwRate instance);
    partial void UpdateBetwRate(BetwRate instance);
    partial void DeleteBetwRate(BetwRate instance);
    partial void InsertDep(Dep instance);
    partial void UpdateDep(Dep instance);
    partial void DeleteDep(Dep instance);
    partial void InsertPo(Po instance);
    partial void UpdatePo(Po instance);
    partial void DeletePo(Po instance);
    #endregion
		
		public DCDataContext() : 
				base(global::TestDiakont.Properties.Settings.Default.TestDiakontConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BetwRate> BetwRates
		{
			get
			{
				return this.GetTable<BetwRate>();
			}
		}
		
		public System.Data.Linq.Table<Dep> Deps
		{
			get
			{
				return this.GetTable<Dep>();
			}
		}
		
		public System.Data.Linq.Table<Po> Pos
		{
			get
			{
				return this.GetTable<Po>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateRate")]
		public int UpdateRate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WageRate", DbType="Int")] System.Nullable<int> wageRate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_pos)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startDate, wageRate, id_pos);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RateInPos")]
		public ISingleResult<RateInPosResult> RateInPos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_pos)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_pos);
			return ((ISingleResult<RateInPosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddPosInDep")]
		public int AddPosInDep([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_dep, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_pos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="Date")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountPos", DbType="Int")] System.Nullable<int> countPos)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_dep, id_pos, startDate, countPos);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PosInDep")]
		public ISingleResult<PosInDepResult> PosInDep([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_dep)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_dep);
			return ((ISingleResult<PosInDepResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SSandBetwRateDate")]
		public int SSandBetwRateDate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_pos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="Date")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="Date")] System.Nullable<System.DateTime> toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_pos, fromDate, toDate);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BetwRate")]
	public partial class BetwRate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_BetwRate;
		
		private System.Nullable<int> _id_rate;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<int> _WageRate;
		
		private System.Nullable<int> _id_pos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_BetwRateChanging(int value);
    partial void Onid_BetwRateChanged();
    partial void Onid_rateChanging(System.Nullable<int> value);
    partial void Onid_rateChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnWageRateChanging(System.Nullable<int> value);
    partial void OnWageRateChanged();
    partial void Onid_posChanging(System.Nullable<int> value);
    partial void Onid_posChanged();
    #endregion
		
		public BetwRate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_BetwRate", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_BetwRate
		{
			get
			{
				return this._id_BetwRate;
			}
			set
			{
				if ((this._id_BetwRate != value))
				{
					this.Onid_BetwRateChanging(value);
					this.SendPropertyChanging();
					this._id_BetwRate = value;
					this.SendPropertyChanged("id_BetwRate");
					this.Onid_BetwRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rate", DbType="Int")]
		public System.Nullable<int> id_rate
		{
			get
			{
				return this._id_rate;
			}
			set
			{
				if ((this._id_rate != value))
				{
					this.Onid_rateChanging(value);
					this.SendPropertyChanging();
					this._id_rate = value;
					this.SendPropertyChanged("id_rate");
					this.Onid_rateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="Date")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="Date")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WageRate", DbType="Int")]
		public System.Nullable<int> WageRate
		{
			get
			{
				return this._WageRate;
			}
			set
			{
				if ((this._WageRate != value))
				{
					this.OnWageRateChanging(value);
					this.SendPropertyChanging();
					this._WageRate = value;
					this.SendPropertyChanged("WageRate");
					this.OnWageRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pos", DbType="Int")]
		public System.Nullable<int> id_pos
		{
			get
			{
				return this._id_pos;
			}
			set
			{
				if ((this._id_pos != value))
				{
					this.Onid_posChanging(value);
					this.SendPropertyChanging();
					this._id_pos = value;
					this.SendPropertyChanged("id_pos");
					this.Onid_posChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dep")]
	public partial class Dep : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_dep;
		
		private string _NameDep;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_depChanging(int value);
    partial void Onid_depChanged();
    partial void OnNameDepChanging(string value);
    partial void OnNameDepChanged();
    #endregion
		
		public Dep()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dep", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_dep
		{
			get
			{
				return this._id_dep;
			}
			set
			{
				if ((this._id_dep != value))
				{
					this.Onid_depChanging(value);
					this.SendPropertyChanging();
					this._id_dep = value;
					this.SendPropertyChanged("id_dep");
					this.Onid_depChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameDep", DbType="NVarChar(MAX)")]
		public string NameDep
		{
			get
			{
				return this._NameDep;
			}
			set
			{
				if ((this._NameDep != value))
				{
					this.OnNameDepChanging(value);
					this.SendPropertyChanging();
					this._NameDep = value;
					this.SendPropertyChanged("NameDep");
					this.OnNameDepChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pos")]
	public partial class Po : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pos;
		
		private string _NamePos;
		
		private System.Nullable<int> _id_dep;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_posChanging(int value);
    partial void Onid_posChanged();
    partial void OnNamePosChanging(string value);
    partial void OnNamePosChanged();
    partial void Onid_depChanging(System.Nullable<int> value);
    partial void Onid_depChanged();
    #endregion
		
		public Po()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pos", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pos
		{
			get
			{
				return this._id_pos;
			}
			set
			{
				if ((this._id_pos != value))
				{
					this.Onid_posChanging(value);
					this.SendPropertyChanging();
					this._id_pos = value;
					this.SendPropertyChanged("id_pos");
					this.Onid_posChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamePos", DbType="NVarChar(MAX)")]
		public string NamePos
		{
			get
			{
				return this._NamePos;
			}
			set
			{
				if ((this._NamePos != value))
				{
					this.OnNamePosChanging(value);
					this.SendPropertyChanging();
					this._NamePos = value;
					this.SendPropertyChanged("NamePos");
					this.OnNamePosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dep", DbType="Int")]
		public System.Nullable<int> id_dep
		{
			get
			{
				return this._id_dep;
			}
			set
			{
				if ((this._id_dep != value))
				{
					this.Onid_depChanging(value);
					this.SendPropertyChanging();
					this._id_dep = value;
					this.SendPropertyChanged("id_dep");
					this.Onid_depChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class RateInPosResult
	{
		
		private int _id_BetwRate;
		
		private System.Nullable<int> _id_rate;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<int> _WageRate;
		
		private System.Nullable<int> _id_pos;
		
		public RateInPosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_BetwRate", DbType="Int NOT NULL")]
		public int id_BetwRate
		{
			get
			{
				return this._id_BetwRate;
			}
			set
			{
				if ((this._id_BetwRate != value))
				{
					this._id_BetwRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rate", DbType="Int")]
		public System.Nullable<int> id_rate
		{
			get
			{
				return this._id_rate;
			}
			set
			{
				if ((this._id_rate != value))
				{
					this._id_rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="Date")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="Date")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WageRate", DbType="Int")]
		public System.Nullable<int> WageRate
		{
			get
			{
				return this._WageRate;
			}
			set
			{
				if ((this._WageRate != value))
				{
					this._WageRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pos", DbType="Int")]
		public System.Nullable<int> id_pos
		{
			get
			{
				return this._id_pos;
			}
			set
			{
				if ((this._id_pos != value))
				{
					this._id_pos = value;
				}
			}
		}
	}
	
	public partial class PosInDepResult
	{
		
		private int _id_ss;
		
		private System.Nullable<int> _id_dep;
		
		private System.Nullable<int> _id_pos;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<int> _CountPos;
		
		private string _NamePos;
		
		public PosInDepResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ss", DbType="Int NOT NULL")]
		public int id_ss
		{
			get
			{
				return this._id_ss;
			}
			set
			{
				if ((this._id_ss != value))
				{
					this._id_ss = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dep", DbType="Int")]
		public System.Nullable<int> id_dep
		{
			get
			{
				return this._id_dep;
			}
			set
			{
				if ((this._id_dep != value))
				{
					this._id_dep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pos", DbType="Int")]
		public System.Nullable<int> id_pos
		{
			get
			{
				return this._id_pos;
			}
			set
			{
				if ((this._id_pos != value))
				{
					this._id_pos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="Date")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountPos", DbType="Int")]
		public System.Nullable<int> CountPos
		{
			get
			{
				return this._CountPos;
			}
			set
			{
				if ((this._CountPos != value))
				{
					this._CountPos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamePos", DbType="NVarChar(MAX)")]
		public string NamePos
		{
			get
			{
				return this._NamePos;
			}
			set
			{
				if ((this._NamePos != value))
				{
					this._NamePos = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
